export const images = [
    "/images/buses/Type1.jpeg",
    "/images/buses/Type1 (2).jpeg",
    "/images/buses/Type1 (3).jpeg",
    "/images/buses/Door.jpeg",
    "/images/buses/Type2.jpeg",
    "/images/buses/Type2 (2).jpeg",
    "/images/buses/Interior (2).jpeg",
    "/images/buses/Type2 (3).jpeg",
    "/images/buses/Type3.jpeg",
    "/images/buses/Seats (2).jpeg",
    "/images/buses/Seats (3).jpeg",
    "/images/buses/Type4.jpeg",
    "/images/buses/Type4 (2).jpeg",
    "/images/buses/Seats.jpeg",
    "/images/buses/Type4 (3).jpeg",
    "/images/buses/Type5.jpeg",
    "/images/buses/Bus Seats.jpeg",
    "/images/buses/Bus Seats (2).jpeg",
    "/images/buses/Interior.jpeg",
    "/images/buses/Interior (3).jpeg",
    "/images/buses/Mini.jpeg",
    "/images/buses/Mini (2).jpeg",
  ];